### ISSUE TITLE
회원가입 정보 중복 시 예외처리

### ISSUE THREAD

**Issue by kw-2sang** [swengineering-team8/O_car#10]
![image](https://user-images.githubusercontent.com/74052457/172793096-9b12ce10-e1c9-4221-a83d-c1eae8312d82.png)

이미 있는 정보로 회원가입 시 위 에러 메시지 출력됩니다.
예외처리 부탁드려요

**Comment by Tung-Pham-Dev** [comment]
예외처리하겠습니다.
