### ISSUE TITLE
로그인 문제

### ISSUE THREAD

**Issue by kw-2sang** [swengineering-team8/O_car#15]
![image](https://user-images.githubusercontent.com/74052457/173175152-c872f9f8-4d26-4cce-ac10-1291ac5e3e93.png)

페이지를 이동하면 로그인 해제가 빈번하게 발생합니다.
확인 부탁드려요!

**Comment by kw-2sang** [comment]
진행중

**Comment by can13any** [comment]
해당 에러 문구는 mysql connection을 중복으로 요청해서 발생한 문제였습니다.
![image](https://user-images.githubusercontent.com/97014341/173380019-f49b4d25-7a17-4028-8316-421f90387daa.png)

로그인 해제에 관한 문제는 
![image](https://user-images.githubusercontent.com/97014341/173380344-53cd23af-6982-4907-b43c-43db8e013b3b.png)
ms 단위로 1분이었던 시간을 60분으로 설정해서 해결했습니다.
