### ISSUE TITLE
auth/update 작동 안됨

### ISSUE THREAD

**Issue by kw-2sang** [swengineering-team8/O_car#20]
auth.js 에서 update route 부분에 SQL 쿼리가 작동을 안하는 것 같습니다.
확인 부탁드려요

**Comment by Tung-Pham-Dev** [comment]
![abc](https://user-images.githubusercontent.com/82079564/173371854-a652fca5-0405-4e19-8bff-1c6b88e2c40e.png)
![acx](https://user-images.githubusercontent.com/82079564/173371874-8d9169ef-9ae9-4360-a83a-a84fecd4d58c.png)
동작했습니다.

**Comment by can13any** [comment]
해당 SQL 문이 비밀번호만 조건으로 들어가서 문제가 되었던 것 같습니다. 수정해서 올리겠습니다.
![image](https://user-images.githubusercontent.com/97014341/173378648-3b85db2a-5c57-49ec-9f31-27f0b91fa0e6.png)
![image](https://user-images.githubusercontent.com/97014341/173378677-704f7ab8-93db-4d08-9035-626dd03b362b.png)
